/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BAvatar: typeof import('bootstrap-vue-next/components/BAvatar')['BAvatar']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    Footer: typeof import('./src/components/admin/Footer.vue')['default']
    Header: typeof import('./src/components/admin/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabCandidates: typeof import('./src/components/admin/TabCandidates.vue')['default']
    TabConfigs: typeof import('./src/components/admin/TabConfigs.vue')['default']
    UserName: typeof import('./src/components/user/UserName.vue')['default']
    Waiting: typeof import('./src/components/user/Waiting.vue')['default']
  }
}
