name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setup git auth
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://${access_token}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global user.email $email
          git config --global user.name $username
      - name: fetch CNAME from dist branch
        run: |
          git fetch origin dist:dist
          git show dist:CNAME > CNAME || echo "CNAME not found, skipping"
      - name: install dependencies
        run: npm install
      - name: build project
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_URL: /
      - name: copy CNAME to dist (if exists)
        run: |
          if [ -f CNAME ]; then
            cp CNAME dist/CNAME
          fi
      - name: copy index.html to 404.html
        run: |
          cp dist/index.html dist/404.html
      - name: deploy to dist
        run: |
          cd dist
          git init
          git checkout -b dist  # Cria a branch dist se não existir
          git add -A
          git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
          git remote add origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git push -f origin dist  # Faz push forçado para a branch dist
